### ISSUE TITLE
NOS App tags dont fill anymore

### ISSUE THREAD

**Issue by mruiter** [bvdbos/com.sasteren.nos#1]
The tags that the NOS app was always filling are empty..

**Comment by Gnillajt** [comment]
> The tags that the NOS app was always filling are empty..

Same here

**Comment by GerardvanEldik** [comment]
As far as I can see has the URL changed on which the video feeds are presented. Perhaps it is better to use this RSS feed: http://feeds.nos.nl/journaal which gives the MP4 URL.

**Comment by bvdbos** [comment]
Unfortunately there's no usable vodcasts for other items. But just committed a fix which also includes the sports-video's.
